"""Add academic structure

Revision ID: fe9df367021d
Revises: 0a735dca48e6
Create Date: 2026-03-21 15:01:28.740125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe9df367021d'
down_revision: Union[str, None] = '0a735dca48e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_rules',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('faculty_id', sa.String(length=20), nullable=False),
    sa.Column('rules_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('degree', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.String(length=20), nullable=False),
    sa.Column('total_hours', sa.SmallInteger(), nullable=False),
    sa.Column('mandatory_hours', sa.SmallInteger(), nullable=False),
    sa.Column('elective_hours', sa.SmallInteger(), nullable=False),
    sa.Column('university_requirements', sa.SmallInteger(), nullable=False),
    sa.Column('tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_regulations',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('program_id', sa.String(length=30), nullable=False),
    sa.Column('registration_rules', sa.Text(), nullable=True),
    sa.Column('pass_fail_rules', sa.Text(), nullable=True),
    sa.Column('absence_policy', sa.Text(), nullable=True),
    sa.Column('mandatory_hours', sa.SmallInteger(), nullable=False),
    sa.Column('elective_hours', sa.SmallInteger(), nullable=False),
    sa.Column('university_requirements', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('program_id', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'courses', 'programs', ['program_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'program_id')
    op.drop_table('study_regulations')
    op.drop_table('programs')
    op.drop_table('academic_rules')
    # ### end Alembic commands ###
